export const GOOGLE_ANALYTICS_ID = 'G-9YLV4PRT5R'
export const GOOGLE_TAG = 'GT-K824C5W'

export const YBUG_CONFIG = {
  id: 'vm2m2s408cha3w2f6pa5',
  primary_color: '#4affa4',
  secondary_color: '#04143c',
  defaults: {
    launcher_position: 'right-middle',
    skip_to: 'feedback',
    hide_branding: true,
    console_log: true,
    video: true,
    type: true,
    type_required: true,
    comment: true,
    comment_required: true,
    email: true,
    email_required: true,
    rating: false,
    rating_required: false,
    name: false,
    name_required: false,
    title: false,
    title_required: false,
    priority: false,
    priority_required: false,
    phone: false,
    phone_required: false,
    nps: false,
    nps_required: false,
    translate: {
      'launcherButton.Title': 'Ask for help',
      'feedbackTypeForm.Heading': 'Ask for help',
      'feedbackTypeForm.Subheading':
        'Have you found a bug or do you have any comments/suggestions about this site?',
      'feedbackTypeForm.ButtonSpecific': 'Select and comment part of this page',
      'feedbackTypeForm.ButtonGeneral': 'General feedback about this page',
      'feedbackForm.Heading': 'Ask for help',
      'feedbackForm.RatingLabel': 'How would you rate your experience?',
      'feedbackForm.TextLabel': 'Comment',
      'feedbackForm.TextPlaceholder': 'Write a comment or describe a problem.',
      'feedbackForm.TitleLabel': 'Title',
      'feedbackForm.TitlePlaceholder': 'Short feedback summary',
      'feedbackForm.TextError': 'This field is required',
      'feedbackForm.EmailLabel': 'Your e-mail',
      'feedbackForm.EmailPlaceholder': 'Your e-mail',
      'feedbackForm.EmailError': 'Please enter a valid e-mail address',
      'feedbackForm.NameLabel': 'Your name',
      'feedbackForm.PriorityLabel': 'Priority',
      'feedbackForm.TypeLabel': 'Type of case',
      'feedbackForm.Types.1': 'Bug',
      'feedbackForm.Types.2': 'Improvement',
      'feedbackForm.Types.3': 'Question',
      'feedbackForm.Types.4': 'Other Feedback',
      'feedbackForm.PhoneLabel': 'Your phone number',
      'feedbackForm.PhoneError': 'Please enter a valid phone number',
      'feedbackForm.NpsLabel':
        'How likely are you to recommend us to a friend or colleague?',
      'feedbackForm.Nps.Unlikely': 'Not likely at all',
      'feedbackForm.Nps.Likely': 'Extremely likely',
      'feedbackForm.ButtonSubmit': 'Submit',
      'feedbackForm.ButtonCancel': 'Back',
      'feedbackForm.RequiredError': 'This field is required',
      'feedbackForm.OptionalText': '(optional)',
      'feedbackForm.AddScreenshot': 'Add screenshot',
      'feedbackForm.EditScreenshot': 'Edit screenshot',
      'feedbackForm.AddVideoClip': 'Record video clip',
      'feedbackForm.PreviewVideoClip': 'Preview video clip',
      'feedbackForm.Consent.Label': 'I agree to the {tos}',
      'feedbackForm.Consent.TosUrl': 'https://ybug.io/terms',
      'feedbackForm.Consent.TosLabel': 'Terms of Service',
      'screenRecorder.Start': 'Start recording',
      'screenRecorder.Stop': 'Stop recording',
      'screenRecorder.Audio.Mute': 'Mute',
      'screenRecorder.Audio.Unmute': 'Unmute',
      'screenRecorder.Audio.NotSupported': 'Audio not supported',
      'screenRecorder.BeforeUnload':
        'Are you sure you want to exit? Any feedback left will not be saved.',
      'videoPreview.RecordAgain': 'Record again',
      'videoPreview.Done': 'Done',
      'highlighter.Cancel': 'Cancel',
      'highlighter.Undo': 'Undo',
      'highlighter.tools.Pencil': 'Pencil',
      'highlighter.tools.Interact': 'Interact',
      'highlighter.tools.Arrow': 'Arrow',
      'highlighter.tools.Rectangle': 'Rectangle',
      'highlighter.tools.ColorPicker': 'Color picker',
      'highlighter.tools.Obfuscate': 'Obfuscate',
      'highlighter.tools.Text': 'Add a comment',
      'highlighter.tools.Text.Placeholder': 'Type a comment',
      'highlighter.tools.Text.Save': 'Save comment',
      'highlighter.Done': 'Done',
      'thankYouModal.Heading': 'Thank You',
      'thankYouModal.Text':
        'Your feedback has been sent successfully. Thank you.',
      'thankYouModal.Button': 'Close',
      'processingModal.Heading': 'Processing',
      'privacyTour.Title': 'Privacy tip',
      'privacyTour.Ok': 'Got it',
      'privacyTour.Obfuscate':
        'Use this tool to obfuscate any personal information before sending your feedback.'
    }
  }
}
